# Generated by Django 6.0.5 on 2026-05-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
